title: "Friction Ridge Image and Features (FRIF) Technology Evaluations (TEs)"
description: "Supplemental information regarding NIST's Friction Ridge Image and Features Technology Evaluations"
baseurl: "/frif"
rooturl: "https://pages.nist.gov"
